
# POST http://localhost:3000/api/users/register
# Content-Type: application/json


# {
#     "name":"Gojo",
#     "email":"gojo@gmail.com",
#     "passwordHashed":"testing"
# }

# POST http://localhost:3000/api/users/signin
# Content-Type: application/json


# {
#     "email":"gojo@gmail.com",
#     "passwordHashed":"testing"
# }

# POST http://localhost:3000/api/gpu/create
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJnb2pvQGdtYWlsLmNvbSIsIm5hbWUiOiJHb2pvIiwiaWF0IjoxNzQ5OTQ1OTY1LCJleHAiOjE3NDk5NDk1NjV9.XIr_9eWBrSvqopUFzfIF0UC1GFTvb5LPr78TC1hRKwM

# {
#     "title":"NVIDIA RTX 3080",
#     "price":300,
#     "condition":"Used",
#     "description":"Barely Used",
#     "imageUrls":["testing"],
#     "city":"Toronto",
#     "province":"ON",
#     "sellerId":1
# }

# GET http://localhost:3000/api/gpu/user
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJnb2pvQGdtYWlsLmNvbSIsIm5hbWUiOiJHb2pvIiwiaWF0IjoxNzQ5OTQ2NjM3LCJleHAiOjE3NDk5NTAyMzd9.Zzv1A3b_WLzX6q7qFu2fDJXIDfSSPf1tzPXQHuIReqg

GET http://localhost:3000/api/gpu/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJnb2pvQGdtYWlsLmNvbSIsIm5hbWUiOiJHb2pvIiwiaWF0IjoxNzQ5OTQ2NjM3LCJleHAiOjE3NDk5NTAyMzd9.Zzv1A3b_WLzX6q7qFu2fDJXIDfSSPf1tzPXQHuIReqg